#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Do not auto-launch sysmaint-panel on Qubes OS.
if [ -f /usr/share/qubes/marker-vm ]; then
  exit 0
fi

/usr/bin/sysmaint-panel
